language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: m8xTLR5GAW1t6xGQ8RbndvLvJBi2IznHEhNge++sbv/AuD/KKWjuYvrzPq4Z7585HJHqcKnqXjD5bkHZS4f42ghqykFarivSmpxMNZeHLLMiJtXtVFqac3gRMfLes5BMYixHSa+au+OgNyOSaVyJFJv+m+Vq7fQIK41EwUQkH50igc9sreYYCZ0M7/AdBTfGNBS0ztpDs4Oe4gXjJupOPEH03CE1OSqD4V8m/gSMJNbSprQXXBiQjmompwvYswTZWMs6zS6VzVjC42hZKykHSz6tngrz+TI20ZsRmsnkT57LYn/Y7sQAYXqwVZ903wb8KISadiK+7tg1ckkmxhqN5y9628Q/C0k9z91cm+F31MuIiShBFy7Ge4RdnIPieEdTPG5T/nzMnO7FD/byTIIZeyupSNK1XqtBdmAof/3AT0L6YfWSVKQyu+LQB5zb+B9Fa8ZKnBn8i+QY5Ip/W8xVupApdJ/N+eZQGnI5WaVVaY85o8Htin4s5q98Rcb+gZ97LvwtapzNxlvNI/sy8zOq3Z7QdY6B3FR4EnmIJYGlBlKNVTmEeayrp8l5f6ZO/BhkW1jGZUGVDtyl5RJrijkWJLB4MtomHsfPKq6c7HpcD2o1D+2n2MXv6a2k4ishLfX2kkDf98b455SekqtHMz9Tb9KSTfDnIdaD8OaVvmJtleE=
  app: sheltered-gorge-50174
  on:
    repo: https://github.com/debrashere/CareerStrategyWithApi.git
